
name: "My Custom Addon"
description: "Addon to handle button input"
version: "1.0.10"
slug: "my_buttons_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: manual
ports:
  8000/tcp: 8000

# options:
#   head:
#     description: "Angle of the head section (0-100)"
#     type: int
#     required: true
#     example: 50
# schema:
#   head: int
